baseURL = '/'
languageCode = 'en-IN'
title = 'Poddar, Ayush'
theme = 'charlolamode'
paginate = 8
enableEmoji = true
Copyright = "Â©2023 Ayush Poddar - ayushpoddar.com"
sectionPagesMenu = 'main'
summaryLength = 30

enableInlineShortcodes = true
enableRobotsTXT = true
pygmentsUseClasses = true

enableGitInfo = true

[frontmatter]
  date = ['date', ':git', 'publishDate']
  expiryDate = ['expiryDate']
  lastmod = [':git', ':fileModTime', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']




